### ISSUE TITLE
Are you interested to contribute in the Odoo Community Association?

### ISSUE THREAD

**Issue by rafaelbn** [OdooCommunityWidgets/website_navigation_megamenu#3]
Hi @lukebranch ,

It looks you could be a very nice contrubutor to OCA. In OCA you will have international visiblity and you will be recognized as profesional Odoo developer. Further more you will be in contact with the best Odoo developers on the world and you could be the international reference for Hong Kong Odoo master developer (review https://github.com/OCA/l10n-china).

Take a look in modules you have that OCA already has:
- https://github.com/OCA/e-commerce/tree/9.0/website_sale_category_megamenu
- https://github.com/OCA/social/pull/18

I would like to carry to OCA:
- https://github.com/OdooCommunityWidgets/website_multi_image
- https://github.com/OdooCommunityWidgets/website_product_attachments

You can check here how to contribute:

**OCA Benefits**: https://odoo-community.org/page/websiteOCA_Benefices
**Contribute**: https://odoo-community.org/page/code

Thanks in advance
Regards

cc @pedrobaeza @jgrandguillaume

**Comment by lukebranch** [comment]
@rafaelbn ,

Thank you for considering me to be a contributor to the OCA. 

Regarding the website_multi_image module this is currently in the process of being re-worked as I would like to remove the current multi-image code and replace it with a dependency on the base_multi_image and product_multi_image modules that @yajo and @pedrobaeza are working on due to the fact these modules will handle the multi-image part of the module in a far more flexible fashion.

There's a PR where you can track the progress on the dependency modules here:

https://github.com/OCA/product-attribute/pull/112

This should be trivial work to replace the multi-image code with the new dependency, however I will need to wait until i've picked apart both modules so that I can re-write it.

Regarding the website_product_attachments, this module is as of yet unfinished, however if you would like to move it to the OCA, i'd be more than happy to try and put in some extra development time to finish it off.

From my understanding the website_multi_image and website_product_attachments should target OCA/website right?

I am also in the early stages of building a module using this library:

https://github.com/pyotp/pyotp

To allow the use of Google Authenticator and Authy among other things for multi-factor authentication in Odoo for logins. 

For this particular project I was planning to target:

OCA/server-tools

would that be a suitable place to submit a PR once i've finished development?

**Comment by rafaelbn** [comment]
Hi @lukebranch ,

Thanks. Please @yajo take care of this PR we will do this.

> Regarding the website_product_attachments, this module is as of yet unfinished, however if you would like to move it to the OCA, i'd be more than happy to try and put in some extra development time to finish it off.
> 
> From my understanding the website_multi_image and website_product_attachments should target OCA/website right?

The idea is to do in 2 ways:
- For website (OCA/website) as you can check here: https://apps.odoo.com/apps/modules/8.0/website_files/
- For website_sale (OCA/ecommerce): like you module.

cc @sergio-incaser @carlos-incaser @pedrobaeza

**Comment by rafaelbn** [comment]
Take a look this functionality: https://apps.odoo.com/apps/modules/8.0/website_files/

**Comment by yajo** [comment]
I'm pretty sure this is way more complete: https://github.com/OCA/website/tree/8.0/website_slides

BTW @lukebranch you will be very welcome to OCA (although we can be at times a bit inquisitive when reviewing), Odoo environment is quite big to work there alone. :wink:

**Comment by rafaelbn** [comment]
- We have this module in OCA which make a fantastic megamenu for **website_sale_categories** https://github.com/OCA/e-commerce/tree/9.0/website_sale_category_megamenu
- Then we could add to OCA this https://github.com/OdooCommunityWidgets/website_navigation_megamenu, only for website, main menu

@Yajo I don't understand

> I'm pretty sure this is way more complete: https://github.com/OCA/website/tree/8.0/website_slides

What is the relation between menus and slides?

**Comment by rafaelbn** [comment]
Ok this issue is clear and I think we can close. Thanks!
